apiVersion: v1
kind: Service
metadata:
  name: bjx-jar-dev
  namespace: qjd-dev
spec:
  ports:
  - name: local-port
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: bjx-jar-dev
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
