---
apiVersion: v1
kind: Service
metadata: 
  name: process 
spec:
  type: NodePort
  ports: 
  - name: process-web
    port: 8080
    nodePort: 8081
  - name: process-debug
    port: 8000
    nodePort: 20011
  selector:
    app: process
