version: "3"
services:
  mysql:
    container_name: my_mysql
    image: mysql:5.6
    restart: always
    ports: 
      - 3306:3306
    volumes:
      - /Users/lhc/srv/docker/mysql5.6/mysql:/var/lib/mysql
      - /Users/lhc/Workspace/kub/compose/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  redis:
    container_name: my_redis
    restart: always
    build:
      context: ./compose/redis
    ports:
      - 6379:6379
  
  zookeeper:
    container_name: my_zookeeper
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181    
      - 8081:8080
  
  rabbitmq:
    container_name: my_rmq
    image: rabbitmq:3-management
    restart: always
    hostname: my_rmq
    ports:
      - 5672:5672
      - 15672:15672
  
  mongo:
    container_name: my_mongo
    image: mongo:4.0
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  activemq:
    container_name: my_activemq
    image: webcenter/activemq
    restart: always
    ports:
      - 8161:8161
      - 61616:61616
      - 61613:61613

  seata-server:
    container_name: seata-server
    restart: always 
    build:
      context: ./compose/seata-server
    ports:
      - "8091:8091"
    environment:
      - SEATA_PORT=8091
      - STORE_MODE=file
      - SEATA_IP=127.0.0.1
  
  flowable-ui:
    container_name: flowable-ui
    restart: always
    image: flowable/flowable-ui
    ports:
      - 8180:8080

